#!/usr/bin/env bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
if [[ $EUID -eq 0 ]]; then
   echo "You must run this script as non-root user with sudo permission." 1>&2
   exit 1
fi
if [ ! $(which sudo) ]; then
	echo 'Please install "sudo" package' 1>&2
	exit 1
fi
if [ ! $(which pip3) ]; then
	echo 'Please install "pip3" package'
	exit 1
fi
if [ -n "$(command -v apt-get)" ]; then
  echo "*** Detected Debian based Linux" 1>&2
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq > /dev/null 2>&1
  sudo apt-get install -yqq ansible > /dev/null 2>&1
fi
if [ -n "$(command -v paru)" ]; then
  echo "*** Detected Arch based Linux" 1>&2
  paru --needed --removemake --cleanafter --noconfirm -Sy ansible
fi
if [ -n "$(command -v ansible-generate)" ]; then
  echo "*** installing ansible generate" 1>&2
  python3 -m pip -q install --no-warn-script-location "ansible-generator" > /dev/null 2>&1
fi
[ -r ~/.vault_pass.txt ] || head -c16 </dev/urandom|xxd -p -u | tee ~/.vault_pass.txt > /dev/null
