#!/usr/bin/env bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
if [ ! $(which sudo) ]; then
	echo 'Please install "sudo" package' 1>&2
	exit 1
fi
if [[ $EUID -eq 0 ]]; then
   echo "You must run this script as non-root user with sudo permission." 1>&2
   exit 1
fi
source "${HOME}/.bashrc"
if [ ! -n "$(command -v gcloud )" ]; then
  if [ -n "$(command -v apt-get)" ]; then
    echo "*** Detected Debian based Linux" 1>&2
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update -qq > /dev/null 2>&1
    sudo apt-get install jq curl libssl-dev -yqq > /dev/null 2>&1
  fi
  if [ ! $(which curl) ]; then
    echo 'Please install "curl" package' 1>&2
    exit 1
  fi
  sudo curl -o /usr/local/lib/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
  sudo tar -C /usr/local/lib -zxf /usr/local/lib/google-cloud-sdk.tar.gz
  sudo bash /usr/local/lib/google-cloud-sdk/install.sh \
    --usage-reporting false \
    --bash-completion true \
    --rc-path ~/.bashrc \
    --path-update true
  sudo rm -r /usr/local/lib/google-cloud-sdk.tar.gz
  sudo chown "$(id -u):$(id -g)" /usr/local/lib/google-cloud-sdk -R
  source "${HOME}/.bashrc"
  [ -f '/usr/local/lib/google-cloud-sdk/path.bash.inc' ] && . '/usr/local/lib/google-cloud-sdk/path.bash.inc'
fi
if [  -n "$(command -v gcloud )" ]; then
  echo "*** 'gcloud' is in path. updating components" 1>&2
  gcloud components update
fi
