#!/usr/bin/env bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
if [ ! $(which sudo) ]; then
	echo 'Please install "sudo" package' 1>&2
	exit 1
fi
if [[ $EUID -eq 0 ]]; then
   echo "You must run this script as non-root user with sudo permission." 1>&2
   exit 1
fi
if [ -n "$(command -v apt-get)" ]; then
  echo "*** Detected Debian based Linux" 1>&2
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq > /dev/null 2>&1
  sudo apt-get install -yqq snapd >/dev/null 2>&1
fi
if [ -n "$(command -v paru)" ]; then
  echo "*** Detected Arch based Linux" 1>&2
  paru --needed --removemake --cleanafter --noconfirm -Sy snapd
fi
if [ ! $(which snap) ]; then
	echo 'Please install "snap" package'
	exit 1
fi
getent group lxd > /dev/null || sudo groupadd lxd
sudo usermod --append --groups lxd "$(id -u)"
if [ ! -n "$(command -v lxc)" ]; then
  sudo snap install core >/dev/null 2>&1 || true
  sudo snap install lxd >/dev/null 2>&1 || true
  echo "PATH=$PATH:/snap/bin" | sudo tee -a /etc/environment > /dev/null
  echo "export PATH=$PATH:/snap/bin" | sudo tee -a /root/.bashrc > /dev/null
fi
export PATH=$PATH:/snap/bin
sudo /bin/bash << _EOF_
source ~/.bashrc
lxd init \
  --auto \
  --network-address="0.0.0.0" \
  --network-port="8443" \
  --trust-password="$(id -u)" \
  --storage-backend="btrfs" \
  --storage-create-loop="60" \
  --storage-pool="default" || true
_EOF_
# [NOTE] => needed to allow lxd containers to access internet
sudo iptables -P FORWARD ACCEPT
