#!/usr/bin/env bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
if [ ! $(which sudo) ]; then
	echo 'Please install "sudo" package' 1>&2
	exit 1
fi
if [[ $EUID -eq 0 ]]; then
   echo "You must run this script as non-root user with sudo permission." 1>&2
   exit 1
fi
if [ -n "$(command -v paru)" ]; then
  echo "*** Detected Arch based Linux" 1>&2
  paru --needed --removemake --cleanafter --noconfirm -Sy yarn nodejs
  exit 0
fi
if [ -n "$(command -v apt-get)" ]; then
  echo "*** Detected Debian based Linux" 1>&2
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get install -yqq apt-utils curl lsb-release wget ca-certificates gnupg2 jq > /dev/null 2>&1
  if [ -n "$(command -v node)" ]; then
    echo "*** node $(node --version) is installed" 1>&2
  else
    wget -qO- https://deb.nodesource.com/setup_12.x | sudo bash - >/dev/null 2>&1
    sudo apt-get install -yqq nodejs >/dev/null 2>&1
  fi
  if [ -n "$(command -v yarn)" ]; then
    echo "*** yarn $(yarn --version) is installed" 1>&2
  else
    curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - >/dev/null 2>&1 
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list > /dev/null
    sudo apt-get update -qq > /dev/null 2>&1
    sudo apt-get install -yqq yarn >/dev/null 2>&1
  fi
fi


