#!/usr/bin/env bash
# https://visualstudio.microsoft.com/visual-cpp-build-tools/
# https://go.microsoft.com/fwlink/?LinkId=691126
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
# export NIGHTLY_VERSION=nightly-2021-01-01
if [ ! $(which sudo) ]; then
	echo 'Please install "sudo" package' 1>&2
	exit 1
fi
if [[ $EUID -eq 0 ]]; then
   echo "You must run this script as non-root user with sudo permission." 1>&2
   exit 1
fi
if [ -n "$(command -v apt-get)" ]; then
  echo "*** Detected Debian based Linux" 1>&2
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq > /dev/null 2>&1
  sudo apt-get install -yqq git curl > /dev/null 2>&1
fi
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- \
-y \
--default-toolchain stable \
--profile default
  if ! grep -q "cargo" ~/.profile; then
  echo '[ -r $HOME/.cargo/env ] && . $HOME/.cargo/env' >> ~/.profile
  source ~/.profile
  fi
source $HOME/.cargo/env
rustup --version
cargo --version 
rustc --version
# rustup update "${NIGHTLY_VERSION}"
# rustup default "${NIGHTLY_VERSION}"
rustup completions bash | sudo tee /etc/bash_completion.d/rustup.bash-completion > /dev/null
rustup component add rust-src
rustup component add rustfmt
rustup component add rls
rustup component add clippy
# cargo install -j $(nproc) cargo-watch cargo-cache cargo-tree systemfd
# cargo install -j $(nproc) petname tojson git-cm git-journal gitoxide
