#!/usr/bin/env bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
if [ ! $(which sudo) ]; then
	echo 'Please install "sudo" package' 1>&2
	exit 1
fi
if [[ $EUID -eq 0 ]]; then
   echo "You must run this script as non-root user with sudo permission." 1>&2
   exit 1
fi
if [ -n "$(command -v paru)" ]; then
  echo "*** Detected Arch based Linux" 1>&2
  paru --needed --removemake --cleanafter --noconfirm -Sy starship
  paru --noconfirm -Sy --asdeps --needed powerline-fonts noto-fonts-emoji
else
  if [ -n "$(command -v apt-get)" ]; then
    echo "*** Detected Debian based Linux" 1>&2
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update -qq > /dev/null 2>&1
    sudo apt-get install jq curl libssl-dev -yqq > /dev/null 2>&1
  fi
fi
if [ ! -n "$(command -v starship )" ]; then
  if [ ! $(which curl) ]; then
    echo 'Please install "curl" package' 1>&2
    exit 1
  fi
  curl -fsSL https://starship.rs/install.sh | sudo bash -s -- --force > /dev/null 2>&1
fi
grep -qF 'starship' ~/.bashrc || echo 'eval "$(starship init bash)"' | tee -a ~/.bashrc > /dev/null
sudo grep -qF 'starship' /root/.bashrc || echo 'eval "$(starship init bash)"' | sudo tee -a /root/.bashrc > /dev/null