#!/usr/bin/env bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
if [ ! $(which sudo) ]; then
	echo 'Please install "sudo" package'
	exit 1
fi
if [ -n "$(command -v apt-get)" ]; then
  echo "*** Detected Debian based Linux"
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq > /dev/null 2>&1
  sudo apt-get install jq curl libssl-dev -yqq > /dev/null 2>&1
fi
curl -fsSL https://starship.rs/install.sh | sudo bash -s -- --force > /dev/null 2>&1
grep -qF 'starship' ~/.bashrc || echo 'eval "$(starship init bash)"' | tee -a ~/.bashrc > /dev/null
sudo grep -qF 'starship' /root/.bashrc || echo 'eval "$(starship init bash)"' | sudo tee -a /root/.bashrc > /dev/null
