#!/usr/bin/env bash
# -*- mode: sh -*-
# vi: set ft=sh :
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
if [ ! $(which sudo) ]; then
	echo 'Please install "sudo" package' 1>&2
	exit 1
fi
if [[ $EUID -eq 0 ]]; then
   echo "You must run this script as non-root user with sudo permission." 1>&2
   exit 1
fi
if [ -n "$(command -v apt-get)" ]; then
  echo "*** Detected Debian based Linux" 1>&2
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get autoremove -yqq --purge > /dev/null 2>&1
  sudo apt-get autoclean -yqq > /dev/null 2>&1
  sudo apt-get clean -qq > /dev/null 2>&1
  sudo rm -rf /var/lib/apt/lists/*
fi
if [ -n "$(command -v pacman)" ]; then
  echo "*** Detected Arch based Linux" 1>&2
  sudo pacman -Qdtq | sudo pacman -Rs - || true
fi