#!/bin/bash
set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
if [ ! $(which sudo) ]; then
	echo 'Please install "sudo" package' 1>&2
	exit 1
fi
echo >&2 "*** key-get: trying to import all missing keys from keyserver.ubuntu.com"
key_server="keyserver.ubuntu.com"
missing_keys=$(sudo apt-get update 2>&1 1>/dev/null|grep 'NO_PUBKEY'|grep -oE '[^ ]+$')
missing_keys=$(echo "$missing_keys" | xargs -n1 | sort -u | xargs )
export key_count=$(echo "$missing_keys"|wc -w)
if [[ "$key_count" -gt 0 ]]; then
  for i in "$missing_keys"; do
  echo >&2 "*** Adding missing GPG key: $i"
  sudo apt-key adv --keyserver  "$key_server" --recv-keys "$i" >/dev/null 2>&1
  if [[ "$?" -eq 0 ]]; then
    gpg -a --export "$i" | sudo apt-key add -
    sudo apt-get update
  else
    echo >&2 "*** Could not find GPG key $i"
  fi
  done
else
  echo >&2 "*** No missing keys detected. Banzai!"
fi
